---
version: '3.9'
services:
  backend:
    command: ["sh", "run.sh"]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://siwins:password@db:5432/siwins_test
      - AUTH0_CLIENT=$AUTH0_CLIENT
      - AUTH0_USER=$AUTH0_USER
      - AUTH0_PWD=$AUTH0_PWD
    image: eu.gcr.io/akvo-lumen/siwins/backend:latest
    network_mode: service:mainnetwork
    restart: always
    volumes:
      - ./backend:/app:delegated
    working_dir: /app
  ci:
    depends_on:
      - backend
      - db
      - frontend
    entrypoint: ./entrypoint.sh
    image: alpine:3.14
    network_mode: service:mainnetwork
    volumes:
      - ./ci/test:/test:ro
    working_dir: /test
  db:
    command: postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off'
      -c 'full_page_writes=off' -c 'max_connections=100' -c 'bgwriter_lru_maxpages=0'
      -c 'client_min_messages=warning'
    restart: always
    volumes:
      - ./db/docker-entrypoint-initdb.d.ci:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./db/script:/script:ro
  frontend:
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - backend
      - db
    image: eu.gcr.io/akvo-lumen/siwins/frontend:latest
    network_mode: service:mainnetwork
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
  mainnetwork:
    image: alpine:3.14.0
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 3000:3000
      - 5000:5000
volumes:
  pg-data: {}
